function f = VecFeature(ftype, W, H)

x = ftype(2); y = ftype(3); w = ftype(4); h = ftype(5);

switch ftype(1)
    case 1
        f = VecBoxSum(x, y, w, h, W, H) - ...
            VecBoxSum(x, y + h, w, h, W, H);
    case 2
        f = VecBoxSum(x+w, y, w, h, W, H) -...
            VecBoxSum(x, y, w, h, W, H);
    case 3
        f = VecBoxSum(x+w, y, w, h, W, H) -...
            VecBoxSum(x, y, w, h, W, H) -...
            VecBoxSum(x+2*w, y, w, h, W, H);
    case 4
        f = VecBoxSum(x+w, y, w, h, W, H) +...
            VecBoxSum(x, y+h, w, h, W, H) -...
            VecBoxSum(x, y, w, h, W, H) -...
            VecBoxSum(x+w, y+h, w, h, W, H);
end
